### ISSUE TITLE
Access to RoutingContext from grpc handlers

### ISSUE THREAD

**Issue by wvuong** [vert-x3/vertx-grpc#138]
#### Describe the feature

FYI, this project is great.

We have some custom `Router` middleware (logging, tracing) that stores some objects in the `RoutingContext` that we are trying to reuse for in our grpc integration since `GrpcServer` can be mounted onto a `Router` instance.  I've run into roadblocks trying to find ways to get at the `RoutingContext` from a `Handler<GrpcServerRequest>`.

#### Use cases

Access to `RoutingContext` from `GrpcServerRequest` would enable us to access the data storage from grpc handlers

#### Contribution

Open to trying a contribution if this feature request would be useful to others.

**Comment by vietj** [comment]
I think that's rather a feature request that should be opened in vertx-web than vertx-grpc
