### ISSUE TITLE
ExceptionHandler,handler,endHandler cannot be registered to StreamObserverReadStream in oneToMany

### ISSUE THREAD

**Issue by tunefun** [vert-x3/vertx-grpc#146]
### Version
4.5.2

### Context

This problem is same to [ExceptionHandler cannot be registered to StreamObserverReadStream in manyToMany #141](https://github.com/vert-x3/vertx-grpc/issues/141#issue-1985671611)

when `io.vertx.grpc.stub.ClientCalls.oneToMany` called if event(exception event, next event, end event) happens before returning the `StreamObserverReadStream ` event is lost.There is no way to register exceptionHandler,handler,endHandler before the call.We can register exceptionHandler,handler,endHandler only after `StreamObserverReadStream` return from `oneToMany`.

https://github.com/vert-x3/vertx-grpc/blob/c5418f6cc4222b47c94147ceb1f285b0095f48ff/vertx-grpc/src/main/java/io/vertx/grpc/stub/ClientCalls.java#L45-L49

**Comment by tsegismont** [comment]
Fixed by bf09f20

**Comment by tunefun** [comment]
@tsegismont when can I expect 4.5.4 to be released?

**Comment by tsegismont** [comment]
> @tsegismont when can I expect 4.5.4 to be released?

It's been released on Feb 22.
