### ISSUE TITLE
Server created with port 0 are not shared

### ISSUE THREAD

**Issue by jo5ef** [vert-x3/vertx-grpc#17]
When a server is created with a random port (e.g. `VertxServerBuilder.forAddress(vertx, host, 0)`), the internal `ServerID` is `"<host>:0"`. Creating more servers with random ports also assigns the same `ServerID`. Since `ServerID` is the key in `VertxServer`'s internal static map, only one random-port-server can be started.

**Comment by vietj** [comment]
is it a grpc issue ?

**Comment by jo5ef** [comment]
It's a vertx-grpc issue, when using the `VertxServerBuilder` and `VertxServer` classes. The grpc lib supports multiple random-port servers.

**Comment by jo5ef** [comment]
Awesome, thank you.
