### ISSUE TITLE
OSGi support

### ISSUE THREAD

**Issue by gadieichhorn** [vert-x3/vertx-grpc#33]
I am trying to resolve this grpc  project in OSGi framework but I see there is no OSGi metadata for this project

1. are you plunning to provide support for OSGi in the future?
2. How do I wrap this as OSGi bundle. It will not resolve becaise of the codegen annotations. I dont think adding the annotation jar to runtime will help, this needs to pe processed and packaged.

I use the bnd plugin to add OSGi info to the jar

> 
> [INFO] --- bnd-maven-plugin:4.0.0:bnd-process (default-bnd-process) @ vertx-grpc ---
> [INFO] Unable to determine whether the meta annotation io.vertx.codegen.annotations.Fluent applied to type io.vertx.grpc.GrpcBidiExchange provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
> [INFO] Unable to determine whether the meta annotation io.vertx.codegen.annotations.GenIgnore applied to type io.vertx.grpc.GrpcBidiExchange provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
> [INFO] Unable to determine whether the meta annotation io.vertx.codegen.annotations.VertxGen applied to type io.vertx.grpc.GrpcBidiExchange provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
> [INFO] Unable to determine whether the meta annotation io.vertx.docgen.Document applied to type io.vertx.grpc.package-info provides bundle annotations as it is not on the project build path. If this annotation does provide bundle annotations then it must be present on the build path in order to be processed
> [INFO] 

Thanks.

**Comment by gadieichhorn** [comment]
here is my bnd file

```
Export-Package: \
    io.vertx.grpc.*;version=${vertx.version};-split-package:=merge-last ,\

Import-Package: \
    io.vertx.codegen.annotations.*;resolution:=optional,\
    !examples, \
	*

```

my pom only depends on vertx-grpc

```
    <dependencies>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-grpc</artifactId>
            <version>${vertx.version}</version>
        </dependency>

    </dependencies>

```

**Comment by pmlopes** [comment]
With vert.x 4.0.0 OSGi metadata will not be included anymore with the distributed jars.
