### ISSUE TITLE
gRPC MetaData to Context

### ISSUE THREAD

**Issue by basalt79** [vert-x3/vertx-grpc#48]
I try to use gRPC within vertx and created a `ServerInterceptor` to get the extraHeader from the metadata object. 

The way to provide this information to the service is to pass the data into `io.grpc.Context` object. this Context can be statically asked for the value. Behind `io.grpc.Context`, there is a `ThreadLocalContextStorage` object.

So the data is bounded to the thread.

Can this be reliable used in a vertx environment? Or is there another "Best Practice" to hand over `io.grpc.Metadata` to the bounded service?

**Comment by vietj** [comment]
could we get this info into the Vert.x context as part of local data ?

**Comment by basalt79** [comment]
hi @vietj 
I created a project to see the usage. https://github.com/basalt79/vertx-grpc
The `SessionIdInterceptor` cannot access the data when it comes to a thread change (timer)
Is there any hint or fix or recommendation on this, because i dont know what the _as part of local data_ is.?
https://github.com/basalt79/vertx-grpc/blob/4ad23e2ef64158e0f180826deaf83fec25e6789a/src/main/java/at/aigner/vertx/grpc/EchoService.java#L37

thx

**Comment by vietj** [comment]
I was thinking of `io.vertx.core.Context` local storage

**Comment by basalt79** [comment]
I use ` Context.current().withValue(SESSION_ID_CTX_KEY, sessionId)` 
to add the value to the current context. But once there is a context switch (in the test case triggered by using a timer) the data is gone.

**Comment by pmlopes** [comment]
@basalt79 I've reviewed the vert.x context affinity for the gRPC client and added an interceptor that does what you're looking for: `ContextServerInterceptor`.

Here's one of the tests:

```java
BindableService service = new VertxGreeterGrpc.GreeterVertxImplBase() {
      @Override
      public Future<HelloReply> sayHello(HelloRequest request) {
        should.assertTrue(Context.isOnEventLoopThread());
        should.assertNotNull(ContextServerInterceptor.get("sessionId"));
        return Future.succeededFuture(HelloReply.newBuilder().setMessage("Hello " + request.getName()).build());
      }
    };

    ServerInterceptor contextInterceptor = new ContextServerInterceptor() {
      @Override
      public void bind(Metadata metadata, ConcurrentMap<String, String> context) {
        context.put("sessionId", metadata.get(SESSION_ID_METADATA_KEY));
      }
    };

    startServer(ServerInterceptors.intercept(service, contextInterceptor))
      .onFailure(should::fail)
      .onSuccess(v -> {
        Metadata extraHeaders = new Metadata();
        extraHeaders.put(Metadata.Key.of("sessionId", Metadata.ASCII_STRING_MARSHALLER), UUID.randomUUID().toString());
        ClientInterceptor clientInterceptor = MetadataUtils.newAttachHeadersInterceptor(extraHeaders);

        channel = VertxChannelBuilder.forAddress(vertx, "localhost", port)
          .intercept(clientInterceptor)
          .usePlaintext()
          .build();

        VertxGreeterGrpc.GreeterVertxStub stub = VertxGreeterGrpc.newVertxStub(channel);
        HelloRequest request = HelloRequest.newBuilder().setName("Julien").build();

        stub.sayHello(request).onComplete(should.asyncAssertSuccess(res -> {
          should.assertTrue(Context.isOnEventLoopThread());
          should.assertEquals("Hello Julien", res.getMessage());
          test.complete();
        }));
      });
```

It also works in you add blocking interceptors, however it is best if this interceptor is one of the first in the chain as gRPC may loose the reference to the metadata object if there's a thread switch at the processing of the interceptors.
