### ISSUE TITLE
File Descriptor leak in VertxChannelBuilder.build

### ISSUE THREAD

**Issue by avgustinmm** [vert-x3/vertx-grpc#54]
**vertx-grpc**: 3.8.4
**OS**: Ubuntu 18.04
**JDK**: openjdk 8 and Oracle JDK 8

**Problem**:
Every VertxChannelBuilder.build method call creates a file descriptor that is not closed until the java process stop. Thus, for instance, if you create and shutdown many ManagedChannel-s you may get in lack of file descriptors.

Simple code to reproduce it is:
> 
      while (true) {
        final VertxChannelBuilder builder = VertxChannelBuilder.forAddress(vertx, "localhost", 80).usePlaintext();
        final ManagedChannel channel = builder.build();
        channel.shutdownNow();
        channel.awaitTermination(10, TimeUnit.SECONDS);
        Thread.sleep(100);
      }
> 
This is a reproducer maven project with main method:
[vertx-grpc-fdleak.zip](https://github.com/vert-x3/vertx-grpc/files/4044321/vertx-grpc-fdleak.zip)
It also dumps file descriptors got by java process after each iteration. 

The problem is, as far as I understand resolving of channel type (in build). It creates channel that is never closed. This seem to produce file descriptor that is not closed.
I tried to change a little bit the code by closing the channel - then the problem was fixed - no file descriptor leakage. What I tried was to change last return with:
>
     final io.netty.channel.EventLoop eventLoop = context.nettyEventLoop();
     final io.netty.channel.Channel tempChannel = transport.channelFactory(false).newChannel();
     final Class<? extends io.netty.channel.Channel> channelType = tempChannel.getClass();
     eventLoop.register(tempChannel);
     tempChannel.close();
     return builder
       .eventLoopGroup(eventLoop)
       .channelType(channelType) // Ugly work around / perhaps contribute change to grpc
       .executor(command -> {
       if (Context.isOnEventLoopThread()) {
         context.executeFromIO(event -> command.run());
       } else {
         command.run();
       }
     }).build();
>

I imagine that the best approach here would be to resolve type with closing the channel (as in the code above) but also the class may be cached for an transport instance.

**Comment by vietj** [comment]
Thanks for the reproducer, it helped fixing the issue.
