### ISSUE TITLE
Server Response WriteStream do not Expose OnCancel Handler Setters

### ISSUE THREAD

**Issue by ctrlshp** [vert-x3/vertx-grpc#71]
I am using the latest 4.0.0-SNAPSHOT of the Vert.x stack. The WriteStream that is passed to a server stream method handler does not expose the `ServerCallStreamObserver.setOnCancelHandler` method so it is impossible to be notified if the client cancels the stream. This was possible to do in the 3.x version of the generated code like so :

```
var observer = (ServerCallStreamObserver<Response>) writeStream.writeObserver();
observer.setOnCancelHandler(() -> handleCancel());
```

Or is there a way to do it that have not been able to find ? Thanks.

**Comment by doctorpangloss** [comment]
You can try the methods on `Context`.

**Comment by pmlopes** [comment]
I've added a getter to bring back the old behavior:

```java
stream.streamObserver()
  .setOnCancelHandler(() -> handleCancel());
```
