### ISSUE TITLE
Could not find vertx-grpc-protoc-plugin-4.0.0.Beta3-windows-x86_64.exe (io.vertx:vertx-grpc-protoc-plugin:4.0.0.Beta3).

### ISSUE THREAD

**Issue by Bleoo** [vert-x3/vertx-grpc#78]
### Questions

I tried to use version 4.0, but the compilation went wrong.
I did it according to the instructions in this document : https://vertx-web-site.github.io/docs/vertx-grpc/java/

using gradle

```
protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:3.2.0"
  }
  plugins {
    grpc {
      artifact = "io.vertx:protoc-gen-grpc-java:1.25.0"
    }
    vertx {
      artifact = "io.vertx:vertx-grpc-protoc-plugin:4.0.0.Beta3"
    }
  }
  generateProtoTasks {
    all()*.plugins {
      grpc
      vertx
    }
  }
}
```

### Version

4.0.0.Beta3

### Context

gradle error:

```
Execution failed for task ':generateProto'.
> Could not resolve all files for configuration ':protobufToolsLocator_vertx'.
   > Could not find vertx-grpc-protoc-plugin-4.0.0.Beta3-windows-x86_64.exe (io.vertx:vertx-grpc-protoc-plugin:4.0.0.Beta3).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/io/vertx/vertx-grpc-protoc-plugin/4.0.0.Beta3/vertx-grpc-protoc-plugin-4.0.0.Beta3-windows-x86_64.exe

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Extra

env: win10, jdk8

**Comment by doctorpangloss** [comment]
```
Execution failed for task ':framework:generateProto'.
> Could not resolve all files for configuration ':framework:protobufToolsLocator_grpc_java'.
   > Could not find vertx-grpc-4.0.0.CR1-osx-x86_64.exe (io.vertx:vertx-grpc:4.0.0.CR1).
     Searched in the following locations:
         https://jcenter.bintray.com/io/vertx/vertx-grpc/4.0.0.CR1/vertx-grpc-4.0.0.CR1-osx-x86_64.exe
```

The issue persists...

**Comment by pmlopes** [comment]
@jponge it seems that the gradle config is wrong. I've no clue how gradle works, so this will take lots of time for me to figure out. Can you have a look and see how we can fix the config?

**Comment by jponge** [comment]
Is the protobuf plugin applied according to https://github.com/google/protobuf-gradle-plugin ?

**Comment by jponge** [comment]
Also what is the `repositories` section like in the file?

**Comment by pmlopes** [comment]
The plugin as in CR1 release works with the maven plugin. But I don't know how to "translate" that to gradle

**Comment by jponge** [comment]
Ok point me to a working Maven example and I'll have a look

**Comment by doctorpangloss** [comment]
@Bleoo here is a workaround you can just use in the meantime. You must have **docker** installed.

 1. Create a file `grpc_java_plugin` with the following contents:

```
#!/usr/bin/env bash
docker run --rm -i maven:latest bash -s <<'EOF'
mvn dependency:get -DremoteRepositories=https://repo1.maven.org/maven2/ -DgroupId=io.vertx -DartifactId=vertx-grpc-protoc-plugin -Dversion=4.0.0.CR1 -Dtransitive=true > /dev/null
MVN_REPO=$(mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
CLASSPATH=$(find ${MVN_REPO} -type f -path "*.jar" | tr '\n' ':')
java -cp "${CLASSPATH}" io.vertx.grpc.protoc.plugin.VertxGrpcGenerator
EOF
```

 2. `chmod +x /path/to/grpc_java_plugin`
 3. Add this to your `protoc` config:

```
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.13.0'
    }
    plugins {
        grpc_java {
            path = "path/to/grpc_java_plugin" // e.g. project.projectDir.absolutePath + "/grpc_java_plugin"
        }
   }
   ...
}
```

**Comment by doctorpangloss** [comment]
I don't think the plugin is working at all. It isn't generating all the files it is supposed to be.

**Comment by pmlopes** [comment]
@jponge it seems that gradle grpc plugin is more strict and doesn't allow running java apps as a protoc plugin. I've followed what salesforce does and updated the build to generate native wrappers for windows, linux and mac on #80

**Comment by toien** [comment]
if `~/.m2/settings.xml` set a central mirror like `https://maven.aliyun.com/nexus/content/repositories/central/` gradle will throw this exception

but when follow link in exception log:
```
Searched in the following locations:
         https://maven.aliyun.com/repository/central/io/vertx/vertx-grpc-protoc-plugin/4.2.3/vertx-grpc-protoc-plugin-4.2.3-osx-x86_64.exe
```

you actually could download it
