### ISSUE TITLE
Add missing type in pluginArtifact documentation for maven generation

### ISSUE THREAD

**Issue by guoyu511** [vert-x3/vertx-grpc#8]
When I tried to compile my `.proto` files using maven, I got the error:

```
[ERROR] 2) io.vertx:protoc-gen-grpc-java:osx-x86_64:1.3.0
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
```

It can be fixed by replacing the `pluginArtifact` section from `io.vertx:protoc-gen-grpc-java:1.3.0:${os.detected.classifier}` to `io.vertx:protoc-gen-grpc-java:1.3.0:exe:${os.detected.classifier}`.

So I think it should be a mistake in the document.

**Comment by Yoshi3003** [comment]
I can confirm that the above solution fixes the problem. Please fix the documentation :D

**Comment by vietj** [comment]
fixed by https://github.com/vert-x3/vertx-grpc/pull/11
