### ISSUE TITLE
Future.setHandler was deprecated, we should use Future.onComplete in generated code.

### ISSUE THREAD

**Issue by liukch** [vert-x3/vertx-grpc#85]
In generated code, there are some codes like this: 
``` java 
public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        case METHODID_FOO:
          serviceImpl.foo((FooRequest) request,
              (io.vertx.core.Promise<FooResponse>) io.vertx.core.Promise.<FooResponse>promise().future().setHandler(ar -> {
                if (ar.succeeded()) {
                  ((io.grpc.stub.StreamObserver<FooResponse>) responseObserver).onNext(ar.result());
                  responseObserver.onCompleted();
                } else {
                  responseObserver.onError(ar.cause());
                }
              }));
          break;
       ................
    }
}
```
The ```promise().future().setHandler``` was deprecated

Vertx version: 3.9.4

**Comment by vietj** [comment]
can we do something for this @pmlopes ?

**Comment by pmlopes** [comment]
This is not a real blocker, but changing it requires a new c++ compiler release. The code that uses `setHandler` can be seen here:

https://github.com/vert-x3/vertx-grpc-java-compiler/blob/master/src/main/cpp/java_generator.cpp#L1269

and here:

https://github.com/vert-x3/vertx-grpc-java-compiler/blob/master/src/main/cpp/java_generator.cpp#L1347

@liukch would you like to make a pull request?

**Comment by liukch** [comment]
@pmlopes  OK, I will try.

**Comment by jitrapon** [comment]
+1

**Comment by pmlopes** [comment]
Fixed by https://github.com/vert-x3/vertx-grpc-java-compiler/pull/25
