### ISSUE TITLE
the code generated by vertx-codegen for vert.x 4 fails!!!

### ISSUE THREAD

**Issue by nx2501** [vert-x3/vertx-grpc#89]
### Version

since '4.0.0-milestone4' to '4.0.2'

### Context

when using the library vertx-grpc (since '4.0.0-milestone4' to '4.0.2') with vert-core (since '4.0.0-milestone4' to '4.0.2') the following error is generated:

error: cannot find symbol
...future().setHandler(ar -> {....
----------^
symbol:   method setHandler((ar)->{ if[...]; } })
...

### Do you have a reproducer?

https://github.com/nx2501/vertx4-grpc-bug.git

### Steps to reproduce

1. configure gradle on local development
2. use java 11
3. down project https://github.com/nx2501/vertx4-grpc-bug
4. cd vertx4-grpc-bug
5. gradle clean build

### Extra

vert-core (since '4.0.0-milestone4' to '4.0.2') replace "setHandler()" with :
"onFailure()"
"onSuccess()"
"onComplete()"

If replace "setHandler()" with "onComplete()" works fine !!!

**Comment by vietj** [comment]
@pmlopes ?

**Comment by pmlopes** [comment]
@nx2501 in vert.x 4 we stopped forking the official compiler and use a "proper" grpc plugin instead, the way you should use it in your gradle (as described in the manual) should be:

```gradle
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.11.4'
    }
    plugins {
        grpc {
            // here the official grpc compiler instead of a fork
            artifact = 'io.grpc:protoc-gen-grpc-java:1.25.0'
        }
        vertx {
            // the proper plugin to the compiler (version should match the stack you use)
            artifact = "io.vertx:vertx-grpc-protoc-plugin:4.0.2"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc
            vertx
        }
        ofSourceSet('main')
    }
}
```
