### ISSUE TITLE
Support for Proto3 Optional Fields

### ISSUE THREAD

**Issue by bbemis017** [vert-x3/vertx-grpc#96]
#### Description

I believe the newest version of [jprotoq](https://github.com/salesforce/grpc-java-contrib/releases) now supports optional proto fields. There is some documentation on their github page on how to set the [feature flag](https://github.com/salesforce/grpc-java-contrib/tree/master/jprotoc/jprotoc) as well. It would be super helpful for the vertx plugin to support this as well.

#### Use cases

 - This feature allows you to represent null values in proto3 without using wrapper messages for individual fields

**Comment by pmlopes** [comment]
Thanks for the heads-up, I'll try to start the upgrade asap.
